name: open_usos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.3

flutter:
  uses-material-design: true

assets: 
  - assets/images/princeton.jpg
